#!/usr/bin/env python2
'''
Replay server for snmp.
See --help for usage.
'''

from twisted.internet import reactor
import Queue
import sys
import mitmproxy
import logging

def main():
    '''
    Parse options, open and read log file, start replay server
    '''
    # uncomment next lines to enable debugging output
    #logging.basicConfig(stream=sys.stderr,
    #                    format='%(levelname)s:%(message)s',
    #                    level=logging.DEBUG)

    (opts, _) = mitmproxy.replay_option_parser(1610)

    if opts.inputfile is None:
        sys.stderr.write("ERROR: Need to specify an input file.\n")
        sys.exit(1)
    else:
        log = mitmproxy.Logger()
        if opts.logfile is not None:
            log.open_log(opts.logfile)

        (serverq, clientq, clientfirst) = mitmproxy.logreader(opts.inputfile)

        sys.stderr.write(
            'Server running on localhost:%d\n' % opts.localport)
        server = mitmproxy.SNMPReplayServer(log, (serverq, clientq),
            opts.delaymod, clientfirst)
        reactor.listenUDP(opts.localport, server)
        reactor.run()
        sys.exit(mitmproxy.exit_code.pop())


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
