#!/usr/bin/env python2
'''
Replay server for SSH.
See --help for usage.
'''

from twisted.internet import reactor
import sys
import mitmproxy
import logging


def main():
    '''
    parse options, open and read log file, start replay server
    '''
    (opts, _) = mitmproxy.ssh_replay_option_parser(2222)

    if opts.debug:
        logging.basicConfig(filename='ssh.log',
                    filemode='w',
                    format='%(levelname)s:%(message)s',
                    level=logging.DEBUG)

    if opts.inputfile is None:
        sys.stderr.write('Need to specify an input file.\n')
        sys.exit(1)

    sys.stderr.write(
        'Server running on localhost:%d\n' % opts.localport)

    factory = mitmproxy.ReplaySSHServerFactory(opts)
    reactor.listenTCP(opts.localport, factory)
    reactor.run()
    sys.exit(mitmproxy.exit_code.pop())


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
