#!/usr/bin/env python2
'''
Telnet (or any other protocol running over port 23) interceptor and logger.
See --help for usage.
'''

from twisted.internet import reactor
import sys
import mitmproxy

# disable reporting of bogus "no-member" errors
# pylint: disable=E1101


class ProxyServer(mitmproxy.ProxyServer):
    '''
    ProxyServer with implemented connect procedure
    '''
    def connect_to_server(self):
        '''
        Connect over raw TCP
        '''
        factory = mitmproxy.ProxyClientFactory(
            self.transmit, self.receive, self.log)
        reactor.connectTCP(self.host, self.port, factory)


def main():
    '''
    Parse options, open log and start proxy server
    '''
    (opts, _) = mitmproxy.proxy_option_parser(23, 2323)

    log = mitmproxy.Logger()
    if opts.logfile is not None:
        log.open_log(opts.logfile)

    sys.stderr.write(
        'Server running on localhost:%d...\n' % (opts.localport))

    factory = mitmproxy.ProxyServerFactory(
        ProxyServer, opts.host, opts.port, log)
    reactor.listenTCP(opts.localport, factory)
    reactor.run()
    sys.exit(mitmproxy.exit_code.pop())


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
