.TH fence_intelmodular 8

.SH NAME
fence_intelmodular - I/O Fencing agent for Intel MFSYS SNMP devices

.SH SYNOPSIS
.B
fence_intelmodular
[\fIOPTION\fR]...

.SH DESCRIPTION
fence_intelmodular is an I/O Fencing agent which can be used with
Intel Modular device (tested on Intel MFSYS25, should work with
MFSYS35 as well). Agent internally uses snmpget, snmpset and snmpwalk command.

fence_intelmodular accepts options on the command line as well as from stdin.
Fenced sends parameters through stdin when it execs the agent.  fence_intelmodular can be run by itself with command line options.  This is useful for testing.

.SH OPTIONS
.TP
\fB-a\fP \fIIPaddress\fR
IP address or hostname of the SNMP device. Can be used any syntax supported by snmpget.
.TP
\fB-h\fP
Print out a help message describing available options, then exit.
.TP
\fB-c\fP \fIcommunity\fR
The read/write community string to be used in the request.
.TP
\fB-n\fP \fIname\fR
Name of port to fence or ifIndex.
.TP
\fB-p\fP \fIpassword\fR
Password for login for SNMP v3 (authentication protocol pass phrase).
.TP
\fB-P\fP \fIpassword\fR
Password for privacy for SNMP v3 (privacy protocol password).
.TP
\fB-S\fP \fIscript\fR
Script to run to retrieve password for login for SNMP v3 (authentication protocol pass phrase).
.TP
\fB-R\fP \fIscript\fR
Script to run to retrieve privacy for SNMP v3 (privacy protocol password).
.TP
\fB-l\fP \fIlogin\fR
Login name for SNMP v3 (security name).
.TP
\fB-d\fP \fIversion\fR
SNMP version (1,2c,3). Default is 1.
.TP
\fB-b\fP \fIauth_protocol\fR
SNMP authentication protocol (MD5|SHA).
.TP
\fB-E\fP \fIsec_level\fR
SNMP security level (noAuthNoPriv|authNoPriv|authPriv).
.TP
\fB-B\fP \fIpriv_protocol\fR
SNMP privacy protocol (DES|AES).
.TP
\fB-u\fP \fIudp_port\fR
UDP/TCP port to use.
.TP
\fB-o\fP \fIaction\fR
The action required.  off (default), on, status, list or monitor. Deprecated
options (enable -> on and disable -> off) can be used too.
.TP
\fB-v\fP
Verbose. Record session to stdout, or debug file if specified (see -D).
.TP
\fB-D\fP
Specifies file, where will be written debug messages from session.
.TP
\fB-V\fP
Print out a version message, then exit.

.SH STDIN PARAMETERS
.TP
\fIagent = < param >\fR
This option is used by fence_node(8) and is ignored by fence_intelmodular.
.TP
\fIipaddr = < param >\fR
IP address or hostname of the SNMP device. Can be used any syntax supported by snmpget.
.TP
\fIcommunity = < param >\fR
The read/write community string to be used in the request.
.TP
\fIport = < param >\fR
Name of port to fence or ifIndex.
.TP
\fIpasswd = < param >\fR
Password for login for SNMP v3 (authentication protocol pass phrase).
.TP
\fIsnmp_priv_passwd\fR
Password for privacy for SNMP v3 (privacy protocol password).
.TP
\fIpasswd_script = < param >\fR
Script to run to retrieve password for login for SNMP v3 (authentication protocol pass phrase).
.TP
\fIsnmp_priv_passwd_script = < param>\fR
Password for privacy for SNMP v3 (privacy protocol password).
.TP
\fIlogin = < param >\fR
Login name for SNMP v3 (security name).
.TP
\fIsnmp_version = < param >\fR
SNMP version (1,2c,3). Default is 1.
.TP
\fIsnmp_auth_prot = < param >\fR
SNMP authentication protocol (MD5|SHA).
.TP
\fIsnmp_sec_level = < param >\fR
SNMP security level (noAuthNoPriv|authNoPriv|authPriv).
.TP
\fIsnmp_priv_prot = < param >\fR
SNMP privacy protocol (DES|AES).
.TP
\fIudpport = < param >\fR
UDP/TCP port to use.
.TP
\fIaction = < param >\fR
The action required.  off (default), on, status, list or monitor. Deprecated
options (enable -> on and disable -> off) can be used too.
.TP
\fIverbose = < param >\fR
Verbose.  Record session to stdout, or debug file if specified (see debug).
.TP
\fIdebug = < param >\fR
Specifies file, where will be written debug messages from session.

.SH SEE ALSO
fence(8), fence_node(8)
